"""add tenants and crawler control plane

Revision ID: 2d908169b4bd
Revises: 04b3bf44d3f1
Create Date: 2026-08-17 09:47:13.685286

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2d908169b4bd"
down_revision = "04b3bf44d3f1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            """
            UPDATE roles
            SET name = 'platform_admin'
            WHERE name = 'admin'
              AND NOT EXISTS (SELECT 1 FROM roles WHERE name = 'platform_admin')
            """
        )
    )
    op.execute(
        sa.text(
            """
            INSERT INTO user_roles (user_id, role_id)
            SELECT ur.user_id, platform.id
            FROM user_roles AS ur
            JOIN roles AS legacy ON legacy.id = ur.role_id AND legacy.name = 'admin'
            CROSS JOIN roles AS platform
            WHERE platform.name = 'platform_admin'
            ON CONFLICT DO NOTHING
            """
        )
    )
    op.execute(
        sa.text(
            """
            INSERT INTO role_permissions (role_id, permission_id)
            SELECT platform.id, rp.permission_id
            FROM role_permissions AS rp
            JOIN roles AS legacy ON legacy.id = rp.role_id AND legacy.name = 'admin'
            CROSS JOIN roles AS platform
            WHERE platform.name = 'platform_admin'
            ON CONFLICT DO NOTHING
            """
        )
    )
    op.execute(sa.text("DELETE FROM roles WHERE name = 'admin'"))
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived')", name=op.f("ck_tenants_ck_tenants_status")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_tenants_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_index(op.f("ix_tenants_status"), "tenants", ["status"], unique=False)
    op.create_table(
        "tenant_invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'member')",
            name=op.f("ck_tenant_invitations_ck_tenant_invitations_role"),
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
            name=op.f("fk_tenant_invitations_invited_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_invitations_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_tenant_invitations_token_hash")),
    )
    op.create_index(
        op.f("ix_tenant_invitations_email"), "tenant_invitations", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_tenant_invitations_tenant_id"), "tenant_invitations", ["tenant_id"], unique=False
    )
    op.create_table(
        "tenant_memberships",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'member')",
            name=op.f("ck_tenant_memberships_ck_tenant_memberships_role"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_memberships_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_tenant_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "user_id", name=op.f("pk_tenant_memberships")),
    )
    op.execute(
        sa.text(
            """
            INSERT INTO tenants (id, name, slug, status, created_by)
            SELECT legacy.tenant_id,
                   'Legacy crawler tenant',
                   'legacy-' || replace(legacy.tenant_id::text, '-', ''),
                   'active',
                   NULL
            FROM (
                SELECT tenant_id FROM crawl_targets
                UNION
                SELECT tenant_id FROM crawl_jobs
            ) AS legacy
            ON CONFLICT (id) DO NOTHING
            """
        )
    )
    op.add_column(
        "crawl_jobs", sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("crawl_jobs", sa.Column("retry_of_job_id", sa.Uuid(), nullable=True))
    op.add_column(
        "crawl_jobs", sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_constraint(op.f("ck_crawl_jobs_status_valid"), "crawl_jobs", type_="check")
    op.create_check_constraint(
        op.f("ck_crawl_jobs_status_valid"),
        "crawl_jobs",
        "status IN ('pending', 'queued', 'running', 'retrying', 'succeeded', 'failed', "
        "'cancelled')",
    )
    op.create_foreign_key(
        op.f("fk_crawl_jobs_retry_of_job_id_crawl_jobs"),
        "crawl_jobs",
        "crawl_jobs",
        ["retry_of_job_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_crawl_jobs_tenant_id_tenants"),
        "crawl_jobs",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("crawl_targets", sa.Column("name", sa.String(length=128), nullable=True))
    op.add_column("crawl_targets", sa.Column("schedule_cron", sa.String(length=128), nullable=True))
    op.add_column(
        "crawl_targets",
        sa.Column("schedule_timezone", sa.String(length=64), server_default="UTC", nullable=False),
    )
    op.add_column(
        "crawl_targets",
        sa.Column("schedule_enabled", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column(
        "crawl_targets", sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "crawl_targets", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.execute(sa.text("UPDATE crawl_targets SET name = target_host WHERE name IS NULL"))
    op.alter_column("crawl_targets", "name", nullable=False)
    op.alter_column("crawl_targets", "schedule_timezone", server_default=None)
    op.alter_column("crawl_targets", "schedule_enabled", server_default=None)
    op.drop_constraint(op.f("uq_crawl_targets_tenant_target_url"), "crawl_targets", type_="unique")
    op.create_index(
        op.f("ix_crawl_targets_archived_at"), "crawl_targets", ["archived_at"], unique=False
    )
    op.create_index(
        op.f("ix_crawl_targets_next_run_at"), "crawl_targets", ["next_run_at"], unique=False
    )
    op.create_unique_constraint(
        "uq_crawl_targets_tenant_url", "crawl_targets", ["tenant_id", "target_url"]
    )
    op.create_foreign_key(
        op.f("fk_crawl_targets_tenant_id_tenants"),
        "crawl_targets",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_check_constraint(
        op.f("ck_crawl_targets_crawl_target_name_not_empty"), "crawl_targets", "name <> ''"
    )
    op.drop_column("crawl_targets", "target_url_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("crawl_targets", sa.Column("target_url_id", sa.UUID(), nullable=True))
    op.execute(sa.text("UPDATE crawl_targets SET target_url_id = id"))
    op.alter_column("crawl_targets", "target_url_id", nullable=False)
    op.drop_constraint(
        op.f("ck_crawl_targets_crawl_target_name_not_empty"), "crawl_targets", type_="check"
    )
    op.drop_constraint(
        op.f("fk_crawl_targets_tenant_id_tenants"), "crawl_targets", type_="foreignkey"
    )
    op.drop_constraint("uq_crawl_targets_tenant_url", "crawl_targets", type_="unique")
    op.drop_index(op.f("ix_crawl_targets_next_run_at"), table_name="crawl_targets")
    op.drop_index(op.f("ix_crawl_targets_archived_at"), table_name="crawl_targets")
    op.create_unique_constraint(
        op.f("uq_crawl_targets_tenant_target_url"),
        "crawl_targets",
        ["tenant_id", "target_url_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("crawl_targets", "archived_at")
    op.drop_column("crawl_targets", "next_run_at")
    op.drop_column("crawl_targets", "schedule_enabled")
    op.drop_column("crawl_targets", "schedule_timezone")
    op.drop_column("crawl_targets", "schedule_cron")
    op.drop_column("crawl_targets", "name")
    op.drop_constraint(op.f("fk_crawl_jobs_tenant_id_tenants"), "crawl_jobs", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_crawl_jobs_retry_of_job_id_crawl_jobs"), "crawl_jobs", type_="foreignkey"
    )
    op.execute(sa.text("UPDATE crawl_jobs SET status = 'failed' WHERE status = 'cancelled'"))
    op.drop_constraint(op.f("ck_crawl_jobs_status_valid"), "crawl_jobs", type_="check")
    op.create_check_constraint(
        op.f("ck_crawl_jobs_status_valid"),
        "crawl_jobs",
        "status IN ('pending', 'queued', 'running', 'retrying', 'succeeded', 'failed')",
    )
    op.drop_column("crawl_jobs", "cancel_requested_at")
    op.drop_column("crawl_jobs", "retry_of_job_id")
    op.drop_column("crawl_jobs", "scheduled_for")
    op.drop_table("tenant_memberships")
    op.drop_index(op.f("ix_tenant_invitations_tenant_id"), table_name="tenant_invitations")
    op.drop_index(op.f("ix_tenant_invitations_email"), table_name="tenant_invitations")
    op.drop_table("tenant_invitations")
    op.drop_index(op.f("ix_tenants_status"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    op.execute(
        sa.text(
            """
            UPDATE roles
            SET name = 'admin'
            WHERE name = 'platform_admin'
              AND NOT EXISTS (SELECT 1 FROM roles WHERE name = 'admin')
            """
        )
    )
    # ### end Alembic commands ###
