from __future__ import annotations

from enum import StrEnum


class TenantStatus(StrEnum):
    ACTIVE = "active"
    ARCHIVED = "archived"


class TenantRole(StrEnum):
    OWNER = "owner"
    ADMIN = "admin"
    MEMBER = "member"


class ErrorCode:
    NOT_FOUND = "TENANT_NOT_FOUND"
    SLUG_CONFLICT = "TENANT_SLUG_CONFLICT"
    MEMBER_NOT_FOUND = "TENANT_MEMBER_NOT_FOUND"
    MEMBER_CONFLICT = "TENANT_MEMBER_CONFLICT"
    OWNER_REQUIRED = "TENANT_OWNER_REQUIRED"
    INVITATION_NOT_FOUND = "TENANT_INVITATION_NOT_FOUND"
    INVITATION_CONFLICT = "TENANT_INVITATION_CONFLICT"
    INVITATION_INVALID = "TENANT_INVITATION_INVALID"
    INVITATION_AUTH_REQUIRED = "TENANT_INVITATION_AUTH_REQUIRED"
